### ISSUE TITLE
After you reset the server, your items do not work.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#11]
I think this is because when you add the attributes, it makes a unique id for each item. When you reset the server, your plugin makes a new attribute modifier, thus a new ID and your plugin won't detect the item. You need some sort of way to identify the item, or store the id. Maybe if you used a yaml file, you could store the item in there. This would generate the same item with the same ID every time. 
 
 Here is the player's item data after reloading the server:
<img width="1450" alt="image" src="https://github.com/loseAlotL/RingCraftPlus/assets/155603248/7abe7c19-343a-4044-92aa-c53453f995de">

Here is the plugin's item data after reloading the server:
<img width="1465" alt="image" src="https://github.com/loseAlotL/RingCraftPlus/assets/155603248/6f706efa-0c6c-4d0c-88e2-6a456484740e">

**Comment by RTClarkV** [comment]
You can see how the IDs are different, making them unique items.

**Comment by loseAlotL** [comment]
ive been trying to figure this out.. for now imma just use the lore to check instead of the whole item

**Comment by RTClarkV** [comment]
That seems to work, considering how much lore each item has and that players in survival cannot modify lore. The only security flaw of this would be a random, different separate item having the same lore, but it's unlikely.
