### ISSUE TITLE
An identifier for each of your commands would be appreciated.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#12]
https://github.com/loseAlotL/RingCraftPlus/blob/b49263dd2a78161c8e429a40bc9cadefb036d535/src/main/resources/plugin.yml#L10

For servers with many plugins, it's common for developers to put some sort of identifier in the first part of a command for each command of that plugin. In world edit that is another "/" (like "//wand" or "//paste"), in MapProtect the identifier is "mp," like "/mpteleport" or "/mpcreate." You could use "rcp" or "RingCraftPlus" in front of your commands.

**Comment by loseAlotL** [comment]
ah ok ill use rcp.blah blah blah
