### ISSUE TITLE
You're killing me smalls 🤣

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#13]
https://github.com/loseAlotL/RingCraftPlus/blob/5069a322c6fdff8344993487e0bdf28e5ffb5e6c/src/main/java/org/randomlima/ringcraftplus/Listeners/RadagastStaff/RadagastStaffRightClick.java#L80

You don't need to copy and paste the same code over and over again. You can code all this cooldown stuff in one class and use that class as a tool.

**Comment by loseAlotL** [comment]
ah... (my single braincell didnt think of this thanks)
