### ISSUE TITLE
You need to create the CooldownManager class.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#15]
https://github.com/loseAlotL/RingCraftPlus/blob/d76a74d56fa7b22ed6c76c80eff11260d33d3593/src/main/java/org/randomlima/ringcraftplus/Listeners/Palantir/PalantirRightClick.java#L22

add:
this.cooldownManager = new CooldownManager(main, seconds);

**Comment by loseAlotL** [comment]
ah ok
