### ISSUE TITLE
Maybe use console logger.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#16]
https://github.com/loseAlotL/RingCraftPlus/blob/40cccb5e7476d8c49424a07c84a7a55342d8f7e2/src/main/java/org/randomlima/ringcraftplus/RingCraftPlus.java#L43

getServer().getConsoleSender().sendMessage("message");

**Comment by loseAlotL** [comment]
oh ok, whats the difference?

**Comment by RTClarkV** [comment]
it prints the message from your plugin. This is "the proper way" to send stuff in console with MC plugins.

**Comment by RTClarkV** [comment]
Maybe it is similar, but I'm just passing down what QuadraticKid told after I used System to print stuff in console a while ago.
