### ISSUE TITLE
Is this for the full version or just for the memes?

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#17]
https://github.com/loseAlotL/RingCraftPlus/blob/75e350a960901422842e0d557439f1382fe039ca/src/main/java/org/randomlima/ringcraftplus/RingCraftPlus.java#L111

This task is not efficient, but if you were just adding something quickly for memes that is okay. So long as you plan on optimizing it or commenting this code out for the main server.

**Comment by loseAlotL** [comment]
yea imma remove it later

**Comment by RTClarkV** [comment]
k 👍
