### ISSUE TITLE
Dear lord you poor soul.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#18]
https://github.com/loseAlotL/RingCraftPlus/blob/75e350a960901422842e0d557439f1382fe039ca/src/main/java/org/randomlima/ringcraftplus/Listeners/GaladrielPhial/GaladrielPhialRightClick.java#L95

Just do this check, it will return true if the entity is a hostile monster:

**public boolean isHostile(Entity entity){
     retrun entity instanceof Monster;
}**

If you ever find yourself making a list this big, think: "surly someone else had this problem and found a better way." Either someone has found a better way, or they already made the list for you to copy and paste.

**Comment by loseAlotL** [comment]
ha, i knew that existed :|
