### ISSUE TITLE
Don't use "§" in the future.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#2]
https://github.com/loseAlotL/RingCraftPlus/blob/9be7fbbf99758a1eb3cc52aad73ead3bef7a5002/src/main/java/org/randomlima/ringcraftplus/Listeners/GondorHorn/GondorHornRightClick.java#L59

I like to use a static class for this instead. I call it like this: **player.sendMessage(Colorize.format("&bThis is blue color.");**
This is just standard procedure in Bukkit.

public class Colorize {
    public static String format(String str){
        return ChatColor.translateAlternateColorCodes('&', str);
    }
}

**Comment by loseAlotL** [comment]
done
