### ISSUE TITLE
BIG ISSUE!! Anyone can get an unlimited number of items!

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#4]
https://github.com/loseAlotL/RingCraftPlus/blob/9be7fbbf99758a1eb3cc52aad73ead3bef7a5002/src/main/java/org/randomlima/ringcraftplus/Commands/GandalfStaff.java#L13

**Any player** can use this command and see it in the help section and **execute it**. **Anyone** can just get an unlimited supply of these items by spamming the command. **research** how to **add permissions** to your commands, or make sure they are **oped** **_before_** giving them the item.

**Comment by loseAlotL** [comment]
fixed (i think)
