### ISSUE TITLE
No need to check for the command name.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#5]
https://github.com/loseAlotL/RingCraftPlus/blob/9be7fbbf99758a1eb3cc52aad73ead3bef7a5002/src/main/java/org/randomlima/ringcraftplus/Commands/SarumanStaff.java#L14

Each of these command classes are only register for 1 command. The code will run only when that class's registered commands are ran. So if the classes each only have 1 register command, you do not need to check for the command's name.

**Comment by loseAlotL** [comment]
i see, i will change that

**Comment by loseAlotL** [comment]
ok i removed all the redundant IFs in each command class
