### ISSUE TITLE
Not an issue, but something to think about.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#6]
https://github.com/loseAlotL/RingCraftPlus/blob/9be7fbbf99758a1eb3cc52aad73ead3bef7a5002/src/main/java/org/randomlima/ringcraftplus/Listeners/GandalfStaff/GandalfStaffShift.java#L39

Because you used the system time, you can see how you repeated many lines of code. How could you make a "cool down tracker" class to make managing all of this repeated code easier? 

For example: You could make a class called CoolDownManager that takes a cool down time in seconds. Instead of copying and pasting the code, you will just use your handy CoolDownManager class.
Try to make it work like this:

**CoolDownManager cooldowns = new CoolDownManager( 45 );** //time in seconds

**coolDowns.startCooldown(UUID);** //starts the cool down of the player.

**cooldowns.isOnCooldown(UUID);** //returns if the player is on cool down yet (true/false).

**Comment by loseAlotL** [comment]
sounds cool, ill see what i can do
