### ISSUE TITLE
This is not how you do permissions.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#7]
https://github.com/loseAlotL/RingCraftPlus/blob/e0e8224ebc6505bdf82c4cf3ee53d776459bd899/src/main/resources/plugin.yml#L16

Try using something like "ringcraftplus.admin" or something. "OP" is just not right.

**Comment by loseAlotL** [comment]
it seems to work tho. ill see

**Comment by RTClarkV** [comment]
yes, but think about someone using your plugin with a dozen other plugins, each with their own permissions. Your plugin needs permissions that make sense and share some sort of name with what it does. "OP" does not really make sense. "ringcraftplus.gandalfstaff" or "rcp.admin" does (rcp short for RingCraftPlus).
