### ISSUE TITLE
else{return} is pointless.

### ISSUE THREAD

**Issue by RTClarkV** [loseAlotL/RingCraftPlus#9]
https://github.com/loseAlotL/RingCraftPlus/blob/e0e8224ebc6505bdf82c4cf3ee53d776459bd899/src/main/java/org/randomlima/ringcraftplus/Listeners/GandalfStaff/GandalfStaffDamage.java#L36

Pointless as in this literally does nothing. You do not always need else statements.

**Comment by loseAlotL** [comment]
oh, idk what i was doing there thanks
